using BTCPayServer.Plugins.Arkade.Wallet;
using NArk.Abstractions.Contracts;
using NArk.Abstractions.VTXOs;
using NBitcoin;

namespace BTCPayServer.Plugins.Arkade.Models;

public class StoreOverviewViewModel
{
    public string? StoreId { get; set; }
    public bool IsLightningEnabled { get; set; }
    public bool IsDestinationSweepEnabled { get; set; }
    public ArkBalancesViewModel? Balances { get; set; }
    public string? WalletId { get; set; }
    public string? Destination { get; set; }
    public bool SignerAvailable { get; set; }
    public string? Wallet { get; set; }
    public string? DefaultAddress { get; set; }
    public bool AllowSubDustAmounts { get; set; }

    /// <summary>
    /// The type of wallet (SingleKey/legacy or HD/mnemonic).
    /// </summary>
    public WalletType WalletType { get; set; }

    /// <summary>
    /// Whether the current user can manage private keys (spend funds, view keys).
    /// True if the wallet was generated by this store OR user is a server admin.
    /// </summary>
    public bool CanManagePrivateKeys { get; set; }
    
    // Service connection status
    public string? ArkOperatorUrl { get; set; }
    public bool ArkOperatorConnected { get; set; }
    public string? ArkOperatorError { get; set; }
    
    public string? BoltzUrl { get; set; }
    public bool BoltzConnected { get; set; }
    public string? BoltzError { get; set; }
    
    // Boltz limits for Lightning - Reverse Swap (Receiving Lightning)
    public long? BoltzReverseMinAmount { get; set; }
    public long? BoltzReverseMaxAmount { get; set; }
    public decimal? BoltzReverseFeePercentage { get; set; }
    public long? BoltzReverseMinerFee { get; set; }
    
    // Boltz limits for Lightning - Submarine Swap (Sending Lightning)
    public long? BoltzSubmarineMinAmount { get; set; }
    public long? BoltzSubmarineMaxAmount { get; set; }
    public decimal? BoltzSubmarineFeePercentage { get; set; }
    public long? BoltzSubmarineMinerFee { get; set; }

    // VTXOs for the overview (recent unspent)
    public IReadOnlyCollection<ArkVtxo> RecentVtxos { get; set; } = [];
    public HashSet<OutPoint> SpendableOutpoints { get; set; } = [];
    public Dictionary<string, ArkContractEntity> VtxoContracts { get; set; } = new();
    public int TotalVtxoCount { get; set; }
}